name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go_version: [1.22]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go_version }}

      - name: Check out code
        uses: actions/checkout@v2

      - name: Build
        run: cd server && go build 

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: binary-${{ matrix.os }}-${{ matrix.version }}
          path: |
            server/server
            server/server.exe
  build_static_files:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Build
        run: zip -r ext_pack.zip extension
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ext_pack
          path: ext_pack.zip
  
  
